// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encoding.proto

package encoding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntMsg struct {
	A                    []int32  `protobuf:"varint,1,rep,packed,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntMsg) Reset()         { *m = IntMsg{} }
func (m *IntMsg) String() string { return proto.CompactTextString(m) }
func (*IntMsg) ProtoMessage()    {}
func (*IntMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac330e3fa468db3c, []int{0}
}

func (m *IntMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntMsg.Unmarshal(m, b)
}
func (m *IntMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntMsg.Marshal(b, m, deterministic)
}
func (m *IntMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntMsg.Merge(m, src)
}
func (m *IntMsg) XXX_Size() int {
	return xxx_messageInfo_IntMsg.Size(m)
}
func (m *IntMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_IntMsg.DiscardUnknown(m)
}

var xxx_messageInfo_IntMsg proto.InternalMessageInfo

func (m *IntMsg) GetA() []int32 {
	if m != nil {
		return m.A
	}
	return nil
}

func init() {
	proto.RegisterType((*IntMsg)(nil), "encoding.IntMsg")
}

func init() { proto.RegisterFile("encoding.proto", fileDescriptor_ac330e3fa468db3c) }

var fileDescriptor_ac330e3fa468db3c = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x4b, 0xce,
	0x4f, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xc4,
	0xb8, 0xd8, 0x3c, 0xf3, 0x4a, 0x7c, 0x8b, 0xd3, 0x85, 0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15,
	0x98, 0x35, 0x58, 0x83, 0x18, 0x13, 0x93, 0xd8, 0xc0, 0x0a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x84, 0xe8, 0x0d, 0x9b, 0x3a, 0x00, 0x00, 0x00,
}
